# K8s namespace to deploy eShopOnDapr in.
namespace: eshopondapr

# Name of host where eShopOnDapr can be accessed.
hostName: localhost

# repo 
eshoprepo: geffzhang

# image version
eshopversion: 1.0.0
