kind: Deployment
apiVersion: apps/v1
metadata:
  name: seq
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: seq
  template:
    metadata:
      labels:
        app: eshop
        service: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: seq-http
            containerPort: 80
            protocol: TCP
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SEQ_API_CANONICALURI
            value: "http://{{ .Values.hostName }}/log/"

---

kind: Service
apiVersion: v1
metadata:
  name: seq
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: seq
spec:
  ports:
    - name: ui
      port: 80
      targetPort: seq-http
  selector:
    service: seq


---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: log-stripprefix
  namespace: eshopondapr
spec:
  stripPrefix:
    prefixes:
      - /log

      
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seq-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: seq
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: "/$1"
    traefik.ingress.kubernetes.io/ssl-redirect: "false"
    traefik.frontend.rule.type: PathPrefix
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: eshopondapr-log-stripprefix@kubernetescrd
spec:
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths: 
      - path: /log/(.*)
        pathType: Prefix
        backend:
          service:
            name: seq
            port: 
              name: ui


 